---

- name: deploy Webserver
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: 'us-east-2'
    # app: 'Voicemail-Transcode'
    # domain: 'voicemail'
    # bucket: 'vandelay-lambda-bucket'
    # zip_file: 'LambdaVoicemailTranscoder'
    # dest_file: "{{ env }}_{{ zip_file }}_{{ git_commit }}.zip"
    # git_commit: "{{ lookup('env', 'WERCKER_GIT_COMMIT') }}"
    # run_id: "{{ lookup('env', 'WERCKER_RUN_ID') }}"
  vars_prompt:
    - name: "DBUser"
      prompt: "Enter the database username"
      private: no
    - name: "DBPassword"
      prompt: "Enter the database password"
      private: yes
    - name: "DBRootPassword"
      prompt: "Enter the database root password"
      private: yes
  roles:
    - role: cloudformation-ansible

  tasks:
    - name: create stack
      cloudformation:
        stack_name: "Webserver"
        state: "present"
        region: "{{ region }}"
        disable_rollback: true
        template: "AWS-WordPress-Template.yaml"
        template_parameters:
          KeyName: "key_name"
          DBUser: "{{ DBUser }}"
          DBPassword: "{{ DBPassword }}"
          DBRootPassword: "{{ DBRootPassword }}"
      register: cloudformation_output
