---

- name: deploy Webserver
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: 'us-east-1'
  vars_prompt:
    - name: "DBUser"
      prompt: "Enter the database username"
      private: no
    - name: "DBPassword"
      prompt: "Enter the database password"
      private: yes
    - name: "DBRootPassword"
      prompt: "Enter the database root password"
      private: yes
  roles:
    - role: ansible
