---
- name: create stack
  cloudformation:
    stack_name: "Webserver"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: "AWS-WordPress-Template.yaml"
    template_parameters:
      KeyName: "key_name"
      DBUser: "{{ DBUser }}"
      DBPassword: "{{ DBPassword }}"
      DBRootPassword: "{{ DBRootPassword }}"
  register: cloudformation_output

- name:
  debug: msg="The WordPress server is online at {{ cloudformation_output.stack_outputs.WebsiteURL }}"
